In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [20]:
# Inportando o arquivo CSV com os dados
df = pd.read_csv('C:/Users/lucas/Downloads/mediasDiarias_modificado.csv')

# Visualizar as primeiras linhas do dataframe
print(df.head())

         Data  PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \
0  2017-01-01                                 0   
1  2017-01-02                                 0   
2  2017-01-03                                 0   
3  2017-01-04                                 0   
4  2017-01-05                                 0   

   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  \
0                                                882       
1                                                880       
2                                                880       
3                                                881       
4                                                882       

   RADIACAO GLOBAL (Kj/m²)  TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)  \
0                      197                                          23.0   
1                      167                                          24.0   
2                      174                                          23.0   
3                      182  

In [27]:
# Verificar se há valores ausentes
print(df.isnull().sum())

# Tratar valores ausentes, se necessário
df = df.dropna()

# Converter a coluna 'Data' para o formato datetime
df['Data'] = pd.to_datetime(df['Data'])

# Categorizar a temperatura
def categorize_temperature(temp):
    if temp > 25:
        return 'quente'
    elif 18 < temp <= 25:
        return 'morna'
    else:
        return 'fria'

df['Categoria'] = df['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'].apply(categorize_temperature)


Data                                                     0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                         0
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)    0
RADIACAO GLOBAL (Kj/m²)                                  0
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)             0
TEMPERATURA DO PONTO DE ORVALHO (°C)                     0
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 0
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 0
UMIDADE RELATIVA DO AR, HORARIA (%)                      0
VENTO, RAJADA MAXIMA (m/s)                               0
VENTO, VELOCIDADE HORARIA (m/s)                          0
Categoria                                                0
dtype: int64


In [28]:
# Selecionar as features (variáveis independentes) e o target (variável dependente)
X = df[['PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 
        'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 
        'RADIACAO GLOBAL (Kj/m²)', 
        'TEMPERATURA DO PONTO DE ORVALHO (°C)', 
        'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 
        'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 
        'UMIDADE RELATIVA DO AR, HORARIA (%)', 
        'VENTO, RAJADA MAXIMA (m/s)', 
        'VENTO, VELOCIDADE HORARIA (m/s)']]
y = df['Categoria']


In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [31]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [32]:
y_pred = model.predict(X_test_scaled)

# Avaliação do modelo
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[ 82  28   0]
 [ 12 187   0]
 [  0   1   0]]
              precision    recall  f1-score   support

        fria       0.87      0.75      0.80       110
       morna       0.87      0.94      0.90       199
      quente       0.00      0.00      0.00         1

    accuracy                           0.87       310
   macro avg       0.58      0.56      0.57       310
weighted avg       0.87      0.87      0.86       310



c:\Users\lucas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\lucas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\lucas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [33]:
def prever_categoria_temperatura(model, scaler, novos_dados):
    # Escalar os novos dados
    novos_dados_scaled = scaler.transform(np.array(novos_dados).reshape(1, -1))
    
    # Fazer a previsão
    categoria_pred = model.predict(novos_dados_scaled)
    
    return categoria_pred[0]



In [35]:
#Sequência dos Dados
##PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
##PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
##RADIACAO GLOBAL (Kj/m²)
##TEMPERATURA DO PONTO DE ORVALHO (°C)
##UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
##UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
##UMIDADE RELATIVA DO AR, HORARIA (%)
##VENTO, RAJADA MAXIMA (m/s)
##VENTO, VELOCIDADE HORARIA (m/s)

# Exemplo de uso da função
novos_dados = [0, 882, 197, 14, 6, 5, 5, 8, 4]
categoria_pred = prever_categoria_temperatura(model, scaler, novos_dados)
print(f'A temperatura prevista é: {categoria_pred}')


A temperatura prevista é: morna


c:\Users\lucas\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
